//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EncuestasV2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class csstdura_encuestaEntities : DbContext
    {
        public csstdura_encuestaEntities()
            : base("name=csstdura_encuestaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<encuaesta_opciones> encuaesta_opciones { get; set; }
        public virtual DbSet<encuaesta_rotacion> encuaesta_rotacion { get; set; }
        public virtual DbSet<encuesta_det_encuesta> encuesta_det_encuesta { get; set; }
        public virtual DbSet<encuesta_edades> encuesta_edades { get; set; }
        public virtual DbSet<encuesta_edocivil> encuesta_edocivil { get; set; }
        public virtual DbSet<encuesta_empresa> encuesta_empresa { get; set; }
        public virtual DbSet<encuesta_encuesta> encuesta_encuesta { get; set; }
        public virtual DbSet<encuesta_explab> encuesta_explab { get; set; }
        public virtual DbSet<encuesta_procesoedu> encuesta_procesoedu { get; set; }
        public virtual DbSet<encuesta_resultados> encuesta_resultados { get; set; }
        public virtual DbSet<encuesta_sexo> encuesta_sexo { get; set; }
        public virtual DbSet<encuesta_tiempopuesto> encuesta_tiempopuesto { get; set; }
        public virtual DbSet<encuesta_tipocontrata> encuesta_tipocontrata { get; set; }
        public virtual DbSet<encuesta_tipojornada> encuesta_tipojornada { get; set; }
        public virtual DbSet<encuesta_tipopersonal> encuesta_tipopersonal { get; set; }
        public virtual DbSet<encuesta_tipopuesto> encuesta_tipopuesto { get; set; }
        public virtual DbSet<encuesta_usuarios> encuesta_usuarios { get; set; }
        public virtual DbSet<encuaesta_centro> encuaesta_centro { get; set; }
        public virtual DbSet<encuaesta_departamento> encuaesta_departamento { get; set; }
        public virtual DbSet<encuaesta_periodo> encuaesta_periodo { get; set; }
    }
}
