//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EncuestasV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class encuesta_empresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public encuesta_empresa()
        {
            this.encuesta_resultados = new HashSet<encuesta_resultados>();
        }
    
        public int emp_id { get; set; }
        public string emp_descrip { get; set; }
        public string emp_estatus { get; set; }
        public string emp_u_alta { get; set; }
        public Nullable<System.DateTime> emp_f_alta { get; set; }
        public string emp_u_cancela { get; set; }
        public Nullable<System.DateTime> emp_f_cancela { get; set; }
        public string emp_no_trabajadores { get; set; }
        public string emp_direccion { get; set; }
        public string emp_telefono { get; set; }
        public string emp_person_contac { get; set; }
        public string emp_correo { get; set; }
        public string emp_cp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<encuesta_resultados> encuesta_resultados { get; set; }
    }
}
