//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EncuestasV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class encuesta_det_encuesta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public encuesta_det_encuesta()
        {
            this.encuesta_resultados = new HashSet<encuesta_resultados>();
        }
    
        public int denc_id { get; set; }
        public Nullable<int> denc_encu_id { get; set; }
        public string denc_descrip { get; set; }
        public string denc_valor { get; set; }
        public string denc_status { get; set; }
        public string denc_u_alta { get; set; }
        public Nullable<System.DateTime> denc_f_alta { get; set; }
        public string denc_u_cancela { get; set; }
        public Nullable<System.DateTime> denc_f_cancela { get; set; }
        public string denc_valor_1 { get; set; }
        public string denc_valor_2 { get; set; }
        public string denc_valor_3 { get; set; }
        public string denc_valor_4 { get; set; }
        public string denc_valor_5 { get; set; }
        public Nullable<int> denc_parte { get; set; }
    
        public virtual encuesta_encuesta encuesta_encuesta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<encuesta_resultados> encuesta_resultados { get; set; }
    }
}
